Repository Team-Muffin/Server, pull requests merged in 2024-06, with the labels that each got.

#3 [feat] API-gateway / api-utils / swagger
  applications/api-gateway/build.gradle
  applications/api-gateway/src/main/java/com/pda/apigateway/ApiGatewayApplication.java
  applications/api-gateway/src/main/java/com/pda/apigateway/config/SwaggerConfig.java
  applications/api-gateway/src/main/resources/application.yml
  applications/user-application/build.gradle
  applications/user-application/docker-compose.yml
  applications/user-application/src/main/java/com/pda/userapplication/UserApplication.java
  applications/user-application/src/main/java/com/pda/userapplication/configs/swagger/SwaggerConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/CorpUser.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/NormalUser.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/User.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/auth/AuthController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/auth/dto/req/SignUpRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/user/UserController.java
  applications/user-application/src/main/java/com/pda/userapplication/services/auth/AuthService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/auth/in/SignUpUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/auth/in/dto/req/SignUpServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/job/JobService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/job/in/GetJobsUseCase.java
  applications/user-application/src/main/resources/application.yml
  settings.gradle
  utils/api-utils/build.gradle
  utils/api-utils/src/main/java/com/pda/apiutils/ApiUtils.java
  utils/api-utils/src/main/java/com/pda/apiutils/GlobalExceptionResponse.java
  utils/api-utils/src/main/java/com/pda/apiutils/GlobalResponse.java
  utils/api-utils/src/main/resources/application.properties
  utils/build.gradle
  utils/exception-handler/build.gradle
  utils/exception-handler/src/main/java/com/pda/exceptionhandler/GlobalExceptionHandler.java
  utils/exception-handler/src/main/java/com/pda/exceptionhandler/exceptions/BadRequestException.java
  utils/exception-handler/src/main/java/com/pda/exceptionhandler/exceptions/ConflictException.java
  utils/tofin-enums/build.gradle
  utils/tofin-enums/src/main/java/com/pda/tofinenums/user/Jobs.java
  utils/tofin-enums/src/main/resources/application.properties
Labels: enhancement

#23 fix: swagger core dependency
  utils/api-utils/build.gradle
  utils/exception-handler/build.gradle
Labels: bug

#22 Merge feature/board-app-init branch into develop
  applications/board-application/.gitignore
  applications/board-application/build.gradle
  applications/board-application/categories.sql
  applications/board-application/src/main/java/com/pda/boardapplication/BoardApplication.java
  applications/board-application/src/main/java/com/pda/boardapplication/config/SwaggerConfig.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/CommentController.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/CommentDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BaseEntity.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardChallengeTag.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardChallengeTagPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardProductTag.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardProductTagPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Bookmark.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BookmarkPk.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Category.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Comment.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Like.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/LikePK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/View.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/ViewPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/exception/ExceptionHandler.java
  applications/board-application/src/main/java/com/pda/boardapplication/exception/NotFoundException.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/CategoryRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/CommentRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/CommentService.java
  applications/board-application/src/main/resources/application.yml
Labels: enhancement

#29 Feature/board api
  applications/api-gateway/src/main/resources/application.yml
  applications/board-application/build.gradle
  applications/board-application/src/main/java/com/pda/boardapplication/config/SecurityConfig.java
  applications/board-application/src/main/java/com/pda/boardapplication/config/SwaggerConfig.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/CommentController.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/CommentDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/UserDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Bookmark.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BookmarkPk.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Comment.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Like.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/LikePK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/View.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/ViewPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BookmarkRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/CommentRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/LikeRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardInteractionService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/CommentService.java
  applications/board-application/src/main/java/com/pda/boardapplication/utils/UserUtils.java
  applications/board-application/src/main/resources/application.yml
Labels: enhancement

#30 fix: modified security util dependencies - AuthUserInfo
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/CommentController.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/UserDto.java
Labels: bug

#34 feat: set user tendency
  applications/user-application/src/main/java/com/pda/userapplication/domains/NormalUser.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/UserController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/dto/req/SetTendencyRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/NormalUserJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/UserDetailEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserDetailEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/services/UserService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/SetTendencyUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/SetTendencyServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveNormalUserOutputPort.java
  utils/tofin-enums/src/main/java/com/pda/tofinenums/user/ServicePurpose.java
Labels: enhancement

#51 Feature/follow
  applications/alert-application/build.gradle
  applications/alert-application/src/main/java/com/pda/alertapplication/AlertApplication.java
  applications/alert-application/src/main/resources/application.yml
  applications/alert-application/src/test/java/com/pda/alertapplication/AlertApplicationTests.java
  applications/credit-application/src/main/java/com/pda/creditapplication/consume/DepositListener.java
  applications/user-application/src/main/java/com/pda/userapplication/configs/security/CustomSecurityConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/FollowController.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/BaseTimeEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/follow/FollowEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/follow/FollowJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/follow/FollowRepository.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/follow/FollowableUser.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserDetailEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserDetailRepository.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserRepository.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserDetailEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/services/FollowService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/FollowUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/FollowOrUnFollowServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/GetFollowableServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/FollowOrUnfollowServiceResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/GetFollowablePagingResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/GetFollowableResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/ReadFollowOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveFollowOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/req/FindFollowableUserRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/res/FindFollowableUserResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/res/FollowPagingResponse.java
  applications/user-application/src/main/resources/application.yml
  applications/user-application/src/main/resources/db/insert_001corpuser.sql
  applications/user-application/src/main/resources/db/insert_002corpfollow.sql
  applications/user-application/src/test/java/com/pda/userapplication/utils/outapi/TestWebClientTest.java
  settings.gradle
Labels: enhancement

#73 Merge branch fix/depl-script into develop
  Jenkinsfile
  scripts/deploy.sh
Labels: enhancement

#74 Merge branch fix/depl-script into develop
  Jenkinsfile
Labels: bug

#75 Merge branch feature/depl-credit into develop
  Jenkinsfile
  applications/credit-application/Dockerfile
  applications/credit-application/build.gradle
  applications/credit-application/src/main/java/com/pda/creditapplication/CreditApplication.java
Labels: enhancement

#77 [feat] 유저 정보 업데이트, [fix] 유저 토큰 Response / 크레딧 deposit
  applications/api-gateway/src/main/resources/application.yml
  applications/credit-application/src/main/java/com/pda/creditapplication/service/CreditService.java
  applications/user-application/build.gradle
  applications/user-application/src/main/java/com/pda/userapplication/configs/converter/MultipartJackson2HttpMessageConverter.java
  applications/user-application/src/main/java/com/pda/userapplication/configs/security/CustomSecurityConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/User.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/UserController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/dto/req/UpdateProfileRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/kafka/KafkaOutputAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/services/UserService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/UpdateUserUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/UpdateProfileServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/TokenInfoServiceResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveUserOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SendUpdateUserOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/req/UserUpdateOutputRequest.java
  applications/user-application/src/main/resources/application.yml
  applications/user-application/src/main/resources/db/insert_001corpuser.sql
  utils/kafka-utils/src/main/java/com/pda/kafkautils/user/UserUpdateDto.java
Labels: bug, enhancement

#81 Merge branch feature/board-search into develop
  applications/board-application/build.gradle
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/controller/ImageController.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardContentDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/ImageDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardCount.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardCountRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardInteractionService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
Labels: enhancement

#91 Merge branch fix/board-api into develop
  applications/board-application/categories.sql
  applications/board-application/docker-compose.yml
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardContentDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BookmarkPk.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardCountRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardInteractionService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
Labels: bug

#92 [Feat] Follow / Subscribe Portfolio
  applications/credit-application/src/main/java/com/pda/creditapplication/controller/CreditController.java
  applications/credit-application/src/main/java/com/pda/creditapplication/controller/dto/req/TransferRequest.java
  applications/credit-application/src/main/java/com/pda/creditapplication/service/CreditService.java
  applications/credit-application/src/main/java/com/pda/creditapplication/service/dto/req/TransferServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/configs/security/CustomSecurityConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/PortfolioSubscribeLog.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/PortfolioController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/UserController.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/api/ApiAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/portfolio/SubscribeLogEntity.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/portfolio/SubscribeLogJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/portfolio/SubscribeLogRepository.java
  applications/user-application/src/main/java/com/pda/userapplication/services/FinfluencerService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/PortfolioService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/PortfolioUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/PortfolioSubscribeServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/UserServiceResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/CreditOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/PortfolioSubscribeOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/req/TransferCreditRequest.java
  applications/user-application/src/test/java/com/pda/userapplication/domains/PortfolioSubscribeLogTest.java
  utils/tofin-security/src/main/java/com/pda/tofinsecurity/hooks/SecurityRequestMatcher.java
Labels: enhancement

#99 [Feat] 포트폴리오 구독 및 조회
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/PortfolioController.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/api/ApiAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserDetailEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/services/PortfolioService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/PortfolioUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/AbstractPortfolio.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/DetailPortfolio.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/GetPortfolioServiceResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/StockResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/GetAssetsOutputPort.java
Labels: enhancement

#102 Merge branch fix/board-api into develop
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/CommentDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardChallengeTag.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardChallengeTagPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardCount.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardProductTag.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/BoardProductTagPK.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Bookmark.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Comment.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Like.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/CommentService.java
  applications/board-application/src/main/java/com/pda/boardapplication/utils/CategoryUtils.java
Labels: enhancement

#103 feat: modify category id(number) to name(string) for board register
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
Labels: bug

#105 [Feat] 환전 / 계좌 조회 / 알림 보내기
  applications/user-application/src/main/java/com/pda/userapplication/configs/security/CustomSecurityConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/domains/UserDetail.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/FinfluencerController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/UserController.java
  applications/user-application/src/main/java/com/pda/userapplication/inadapters/controllers/dto/req/ExchangeRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/api/ApiAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserDetailDetailJpaAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/entities/user/UserDetailRepository.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/jpa/mapper/UserDetailEntityMapper.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/kafka/KafkaOutputAdapter.java
  applications/user-application/src/main/java/com/pda/userapplication/outadapters/kafka/config/KafkaProducerConfig.java
  applications/user-application/src/main/java/com/pda/userapplication/services/AssetService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/FinfluencerService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/FollowService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/PortfolioService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/UserService.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/ConnectAssetUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/FinfluencerUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/GetUserAssetsUseCase.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/req/ExchangeServiceRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/in/dto/res/AssetInfoServiceResponse.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/GetAssetsOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/ReadNormalUserOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/ReadUserDetailOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveAssetsOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveNormalUserOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SaveUserDetailOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SendAlertMessageOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/SendUpdateUserOutputPort.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/req/SendMessageRequest.java
  applications/user-application/src/main/java/com/pda/userapplication/services/out/dto/req/TransferCashRequest.java
  applications/user-application/src/main/resources/db/insert_007admin.sql
Labels: enhancement

#106 Merge branch feature/board-update into develop
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/dto/BoardDto.java
  applications/board-application/src/main/java/com/pda/boardapplication/entity/Board.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardChallengeTagRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/repository/BoardProductTagRepository.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/CommentService.java
Labels: enhancement

#109 Merge branch fix/board-tag into develop
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
Labels: bug

#123 Merge branch feature/product-tag into develop
  applications/api-gateway/scripts/reload.sh
  applications/board-application/src/main/java/com/pda/boardapplication/controller/BoardController.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardInteractionService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/BoardService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/CommentService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/ProducerService.java
  applications/board-application/src/main/java/com/pda/boardapplication/service/UserUpdateService.java
  applications/board-application/src/main/resources/application.yml
  applications/eureka-server/src/main/resources/application.yml
Labels: enhancement
